# Generated by Django 5.0.4 on 2024-04-22 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todo_options_user_email_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.RegexValidator(message="Номер телефона необходимо ввести в формате: '+996xxxxxxxxx'.", regex='^\\+996\\d{9}$')], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
