# Generated by Django 5.0.4 on 2024-04-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
